### ISSUE TITLE
After last update it does not work anymore

### ISSUE THREAD

**Issue by joeduck** [ottopaulsen/MMM-MQTT#19]
Hi,

sadly does not work since last update:

`ReferenceError: log is not defined
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-MQTT/node_helper.js:105:9)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)`

**Comment by ottopaulsen** [comment]
Sorry about that. Should be fixed now.
Thanks for the good bug report.

Otto
