### ISSUE TITLE
Blank screen after last update

### ISSUE THREAD

**Issue by Mattmanandeddie** [ottopaulsen/MMM-MQTT#44]
I am only getting a blank screen after the last update. I have removed from /modules directory and recloned and installed also I have tried with different config files. I have a local ip address set 192.168.1.100 for MQTT server but error log for MM is below.

[PM2][ERROR] Process 0 not found
[2021-04-24 14:38:00.654] [ERROR]  WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/modules/MMM-MQTT/utils.js:2
  return "" + server.address + ":" + (server.port ?? "1883") + server.user;
                                                   ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MQTT/mqtt_helper.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[2021-04-24 14:38:00.664] [ERROR]  App threw an error during load
[2021-04-24 14:38:00.665] [ERROR]  /home/pi/MagicMirror/modules/MMM-MQTT/utils.js:2
  return "" + server.address + ":" + (server.port ?? "1883") + server.user;
                                                   ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MQTT/mqtt_helper.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[2021-04-24 14:38:00.668] [ERROR]  /home/pi/MagicMirror/modules/MMM-MQTT/utils.js:2
  return "" + server.address + ":" + (server.port ?? "1883") + server.user;
                                                   ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MQTT/mqtt_helper.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)

**Comment by Mattmanandeddie** [comment]
I fixed it for myself. I changed the line in MMM-MQTT/utils.js
From:
return "" + server.address + ":" + (server.port ?? "1883") + server.user;
To:
return "" + server.address + ":" + server.port + server.user;

**Comment by ottopaulsen** [comment]
Hi, could you please check what berdion of node you have?

`node —version`

**Comment by ottopaulsen** [comment]
If you download the latest version, this problem is fixed.

Otto
